name = "MATLABDiffEq"
uuid = "e2752cbe-bcf4-5895-8727-84ebc14a76bd"
version = "1.4.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
MATLAB = "10e44e05-a98a-55b3-a45b-ba969058deb6"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
DiffEqBase = "6.122"
JET = "0.9, 0.10, 0.11"
MATLAB = "0.8, 0.9"
ModelingToolkit = "8, 9, 10, 11"
PrecompileTools = "1"
Reexport = "0.2, 1.0"
julia = "1.6"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ParameterizedFunctions", "JET"]
